name: quran_listienning
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # Internet
  dio: ^3.0.0
  # Flutter clock
  flutter_analog_clock: ^0.1.1
  #  Database
  floor: ^1.0.1
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  sqflite: ^2.0.0+3
  animated_splash_screen: ^1.0.1+2
  http: ^0.12.2
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  intl: ^0.17.0
  assets_audio_player: ^2.0.13+1
  page_transition: ^1.1.7+2
  move_to_background: ^1.0.1
  flutter_staggered_animations: ^0.1.2
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.10.1
  cached_network_image: ^2.5.0
  flutter_launcher_icons: ^0.8.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  like_button: ^1.0.4
  get: ^4.1.4
  flutter_spinkit: ^5.0.0
  rflutter_alert: ^2.0.2
  scrollable_positioned_list: ^0.1.10
  visibility_detector: ^0.1.5
  image_picker: ^0.7.4
  clipboard: ^0.1.2+8
  share: ^0.6.5+4
  fluttertoast: ^3.1.3
  flutter_parsed_text: ^1.2.5
  flutter_compass: ^0.4.2
  html_character_entities: ^0.1.2+4
  hooks_riverpod: ^0.12.4
  pdf: 2.1.0
  open_file: 2.1.1
  geolocator: ^6.0.3
  flutter_barcode_scanner: ^2.0.0
  encrypt: any
  qr_flutter: any
  #qr_flutter: ^3.2.0
  barcode_scan: any
  flutter_linkify: any

dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/images/icon.png
    - assets/json_files/Book.json
    - assets/json_files/Chapter.json
    - assets/json_files/Collection.json
    - assets/json_files/1SahihBukhari.json
    - assets/json_files/2SahihMuslim.json
    - assets/json_files/3AnNasai.json
    - assets/json_files/4AbuDawood.json
    - assets/json_files/5JamiatTirmidhi.json
    - assets/json_files/6IbnMajah.json
    - assets/json_files/7MalikMuwatta.json
    - assets/json_files/8MusnadAhmed.json
    - assets/json_files/9RiyadUsSaliheen.json
    - assets/json_files/10ShamailTirmidhi.json
    - assets/json_files/11AlAdabAlMufrad.json
    - assets/json_files/12BulughAlMaram.json
    - assets/json_files/13Nawawi.json
    - assets/json_files/14QudsiHadith.json

